export enum OtpPurpose {
    REGISTRATION = "REGISTRATION",
    PASSWORD_RESET = "PASSWORD_RESET",
    FORGOT_PASSWORD="FORGOT_PASSWORD"
}
export const OTP_EXPIRY_SECONDS = 60;
export const TEMP_USER_EXPIRY_SECONDS = 1 * 60;
// export const OTP_PREFIX = "otp:";